# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [127]:
import numpy as np #Load all the numpy packages



### A Note About "import as"

    import * 
This loads all submodules. Note: this is a waste of memory when incorporated into deployed code. 
We'll use it here by example - it's fine to use for learning purposes and legibility.

As we'll see later, the proper convention is to use:

    import numpy as np
    
And then to specifically call needed methods:

<img src="http://note.io/1juA60F">



### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [128]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [129]:
# Note the way each array is printed:
a,b,c,d


(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[8, 1, 4, 9],
         [7, 3, 7, 9],
         [3, 5, 9, 4]],
 
        [[6, 7, 9, 7],
         [8, 7, 8, 6],
         [2, 3, 9, 8]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [130]:
## Arithmetic in arrays is element wise

In [131]:
 a = np.array( [20,30,40,50] )
 b = np.arange( 4 )
 b

array([0, 1, 2, 3])

In [132]:
 c = a-b
 c

array([20, 29, 38, 47])

In [133]:
 b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [134]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [135]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [136]:
a[2:5]

array([ 4,  9, 16])

In [137]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [138]:
b = np.random.randint(1,100,(4,4))

In [139]:
b

array([[49, 84, 25, 60],
       [ 1, 92, 86, 56],
       [ 4,  8, 44, 77],
       [99, 81, 65, 14]])

In [140]:
# Guess the output
print(b[2,3])
print(b[0,0])


77
49


In [141]:
b[0:3,1],b[:,1]

(array([84, 92,  8]), array([84, 92,  8, 81]))

In [142]:
b[1:3,:]

array([[ 1, 92, 86, 56],
       [ 4,  8, 44, 77]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [143]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [144]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [145]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [146]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  0.479167  0.865135 -1.360710  0.166347
2014-01-02  0.464220  1.157887  0.357518 -0.570971
2014-01-03  0.806039  1.477026 -1.333826  0.485800
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481
2014-01-05 -0.217865 -0.533390 -1.705967  0.264683
2014-01-06  0.829533  1.340637 -0.217381  1.085904

In [147]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [148]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [149]:
df.head()

A         B         C         D
2014-01-01  0.479167  0.865135 -1.360710  0.166347
2014-01-02  0.464220  1.157887  0.357518 -0.570971
2014-01-03  0.806039  1.477026 -1.333826  0.485800
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481
2014-01-05 -0.217865 -0.533390 -1.705967  0.264683

In [150]:
df.tail()

A         B         C         D
2014-01-02  0.464220  1.157887  0.357518 -0.570971
2014-01-03  0.806039  1.477026 -1.333826  0.485800
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481
2014-01-05 -0.217865 -0.533390 -1.705967  0.264683
2014-01-06  0.829533  1.340637 -0.217381  1.085904

In [151]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [152]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.721199  0.531056 -1.026283  0.203547
std    0.717658  1.087843  0.894019  0.571776
min   -0.217865 -1.120961 -1.897334 -0.570971
25%    0.467957 -0.183759 -1.619653 -0.116274
50%    0.642603  1.011511 -1.347268  0.215515
75%    0.823659  1.294950 -0.496492  0.430521
max    1.966098  1.477026  0.357518  1.085904

In [153]:
df.sort_values(by='B')
df

A         B         C         D
2014-01-01  0.479167  0.865135 -1.360710  0.166347
2014-01-02  0.464220  1.157887  0.357518 -0.570971
2014-01-03  0.806039  1.477026 -1.333826  0.485800
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481
2014-01-05 -0.217865 -0.533390 -1.705967  0.264683
2014-01-06  0.829533  1.340637 -0.217381  1.085904

### Selection

In [154]:
df[['A','B']]

A         B
2014-01-01  0.479167  0.865135
2014-01-02  0.464220  1.157887
2014-01-03  0.806039  1.477026
2014-01-04  1.966098 -1.120961
2014-01-05 -0.217865 -0.533390
2014-01-06  0.829533  1.340637

In [155]:
df[0:3]

A         B         C         D
2014-01-01  0.479167  0.865135 -1.360710  0.166347
2014-01-02  0.464220  1.157887  0.357518 -0.570971
2014-01-03  0.806039  1.477026 -1.333826  0.485800

In [156]:
# By label
df.loc[dates[0]]

A    0.479167
B    0.865135
C   -1.360710
D    0.166347
Name: 2014-01-01 00:00:00, dtype: float64

In [157]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  0.479167  0.865135
2014-01-02  0.464220  1.157887
2014-01-03  0.806039  1.477026
2014-01-04  1.966098 -1.120961
2014-01-05 -0.217865 -0.533390
2014-01-06  0.829533  1.340637

In [158]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02  1.157887
2014-01-03  1.477026
2014-01-04 -1.120961

In [159]:
# Fast access to scalar
df.at[dates[1],'B']

1.1578872466903471

In [160]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481
2014-01-05 -0.217865 -0.533390 -1.705967  0.264683
2014-01-06  0.829533  1.340637 -0.217381  1.085904

### Boolean Indexing

In [161]:
df[df.A < 0] # Basically a 'where' operation

A        B         C         D
2014-01-05 -0.217865 -0.53339 -1.705967  0.264683

### Setting

In [162]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [163]:
df_posA

A         B         C         D
2014-01-01  0.479167  0.865135 -1.360710  0.166347
2014-01-02  0.464220  1.157887  0.357518 -0.570971
2014-01-03  0.806039  1.477026 -1.333826  0.485800
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481
2014-01-05  0.217865  0.533390  1.705967 -0.264683
2014-01-06  0.829533  1.340637 -0.217381  1.085904

In [164]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [165]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [166]:
df['F'] = s1

In [167]:
df

A         B         C         D    F
2014-01-01  0.479167  0.865135 -1.360710  0.166347  NaN
2014-01-02  0.464220  1.157887  0.357518 -0.570971  1.0
2014-01-03  0.806039  1.477026 -1.333826  0.485800  2.0
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481  3.0
2014-01-05 -0.217865 -0.533390 -1.705967  0.264683  4.0
2014-01-06  0.829533  1.340637 -0.217381  1.085904  5.0

### Missing Data

In [168]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [169]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [170]:
df1

A         B         C         D    F    E
2014-01-01  0.479167  0.865135 -1.360710  0.166347  NaN  1.0
2014-01-02  0.464220  1.157887  0.357518 -0.570971  1.0  1.0
2014-01-03  0.806039  1.477026 -1.333826  0.485800  2.0  NaN
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481  3.0  NaN

In [171]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [172]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean   0.721199  0.531056 -1.026283  0.203547  3.000000
std    0.717658  1.087843  0.894019  0.571776  1.581139
min   -0.217865 -1.120961 -1.897334 -0.570971  1.000000
25%    0.467957 -0.183759 -1.619653 -0.116274       NaN
50%    0.642603  1.011511 -1.347268  0.215515       NaN
75%    0.823659  1.294950 -0.496492  0.430521       NaN
max    1.966098  1.477026  0.357518  1.085904  5.000000

In [173]:
df.mean(),df.mean(1) # Operation on two different axes

(A    0.721199
 B    0.531056
 C   -1.026283
 D    0.203547
 F    3.000000
 dtype: float64, 2014-01-01    0.037485
 2014-01-02    0.481731
 2014-01-03    0.687008
 2014-01-04    0.347464
 2014-01-05    0.361492
 2014-01-06    1.607739
 Freq: D, dtype: float64)

### Applying functions

In [174]:
df

A         B         C         D    F
2014-01-01  0.479167  0.865135 -1.360710  0.166347  NaN
2014-01-02  0.464220  1.157887  0.357518 -0.570971  1.0
2014-01-03  0.806039  1.477026 -1.333826  0.485800  2.0
2014-01-04  1.966098 -1.120961 -1.897334 -0.210481  3.0
2014-01-05 -0.217865 -0.533390 -1.705967  0.264683  4.0
2014-01-06  0.829533  1.340637 -0.217381  1.085904  5.0

In [175]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  0.479167  0.865135 -1.360710  0.166347   NaN
2014-01-02  0.943387  2.023022 -1.003193 -0.404624   1.0
2014-01-03  1.749427  3.500048 -2.337019  0.081176   3.0
2014-01-04  3.715525  2.379087 -4.234352 -0.129305   6.0
2014-01-05  3.497661  1.845697 -5.940319  0.135378  10.0
2014-01-06  4.327193  3.186334 -6.157700  1.221282  15.0

In [176]:
df.apply(lambda x: x.max() - x.min())

A    2.183963
B    2.597988
C    2.254851
D    1.656875
F    4.000000
dtype: float64

In [177]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [178]:
np.random.randn(10,4)

array([[-0.62772081, -0.44326842,  1.92706129, -0.8564745 ],
       [-0.61334954,  0.37829408,  2.11873541, -0.51558064],
       [ 1.51616156,  0.59834405,  0.64914367, -0.75477975],
       [-0.13544797, -0.66703425,  0.39538401,  0.67773798],
       [-0.73266132, -0.72547042,  0.17984282, -0.89987544],
       [-1.07243521,  1.46237396,  0.11431891,  0.39699819],
       [ 0.16639629, -0.47376154,  1.0820266 , -0.80814694],
       [-0.09623769,  0.1677588 , -0.21652495,  0.20608268],
       [-0.89855144,  0.13247574,  1.71024213, -0.63680976],
       [ 0.05227426,  0.74676966,  0.30575333,  1.21709136]])

In [179]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -0.318275 -1.000827 -1.424906 -0.459811
1 -1.416148  1.555569 -1.053627 -0.673111
2  2.737421  0.599673 -0.595056  0.648795
3  0.011163 -0.646994 -1.838412  0.963340
4 -0.485415 -0.268917  0.428871  0.039888
5  0.351829  0.514867  0.674741  0.553628
6  0.264180 -0.823257  0.089877 -0.325774
7  0.359284 -1.541944  0.484430  0.621780
8 -0.161355 -0.748673  2.470107 -0.116105
9 -1.254337 -1.687907  0.165766 -0.181366

In [180]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -0.318275 -1.000827 -1.424906 -0.459811
 1 -1.416148  1.555569 -1.053627 -0.673111
 2  2.737421  0.599673 -0.595056  0.648795,
           0         1         2         3
 3  0.011163 -0.646994 -1.838412  0.963340
 4 -0.485415 -0.268917  0.428871  0.039888
 5  0.351829  0.514867  0.674741  0.553628
 6  0.264180 -0.823257  0.089877 -0.325774,
           0         1         2         3
 7  0.359284 -1.541944  0.484430  0.621780
 8 -0.161355 -0.748673  2.470107 -0.116105
 9 -1.254337 -1.687907  0.165766 -0.181366]

In [181]:
pd.concat(pieces)

0         1         2         3
0 -0.318275 -1.000827 -1.424906 -0.459811
1 -1.416148  1.555569 -1.053627 -0.673111
2  2.737421  0.599673 -0.595056  0.648795
3  0.011163 -0.646994 -1.838412  0.963340
4 -0.485415 -0.268917  0.428871  0.039888
5  0.351829  0.514867  0.674741  0.553628
6  0.264180 -0.823257  0.089877 -0.325774
7  0.359284 -1.541944  0.484430  0.621780
8 -0.161355 -0.748673  2.470107 -0.116105
9 -1.254337 -1.687907  0.165766 -0.181366

In [182]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -0.318275 -1.000827 -1.424906 -0.459811
1 -1.416148  1.555569 -1.053627 -0.673111
2  2.737421  0.599673 -0.595056  0.648795
3  0.011163 -0.646994 -1.838412  0.963340
4 -0.485415 -0.268917  0.428871  0.039888
5  0.351829  0.514867  0.674741  0.553628
6  0.264180 -0.823257  0.089877 -0.325774
7  0.359284 -1.541944  0.484430  0.621780
8 -0.161355 -0.748673  2.470107 -0.116105
9 -1.254337 -1.687907  0.165766 -0.181366

### Grouping


In [183]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [184]:
df

A      B         C         D
0  foo    one  0.127046  0.651278
1  bar    one  0.989410  1.460669
2  foo    two -0.686927 -1.298271
3  bar  three  0.409656  1.825584
4  foo    two  0.108865  0.410870
5  bar    two  0.368562  0.656611
6  foo    one  0.663605  0.128809
7  foo  three  0.583871 -1.763805

In [215]:
pd.pivot_table(df, index=['A'], columns=['B'], values='C', aggfunc='max')

B         one     three       two
A                                
bar  0.989410  0.409656  0.368562
foo  0.663605  0.583871  0.108865

In [213]:
df.pivot(index='A', columns='B', aggfunc='sum')

TypeError: pivot() got an unexpected keyword argument 'aggfunc'

In [185]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one    0.989410  1.460669
    three  0.409656  1.825584
    two    0.368562  0.656611
foo one    0.790651  0.780087
    three  0.583871 -1.763805
    two   -0.578062 -0.887401

### Reshaping

In [186]:
# You can also stack or unstack levels

In [187]:
a = df.groupby(['A','B']).sum()

In [219]:
df.

SyntaxError: invalid syntax (<ipython-input-219-d230d845cd15>, line 1)

In [188]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar  0.989410  0.409656  0.368562  1.460669  1.825584  0.656611
foo  0.395326  0.583871 -0.289031  0.390043 -1.763805 -0.443700

### Time Series


In [189]:
import pandas as pd
import numpy as np

In [190]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [191]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [192]:
ts

2014-01-01 00:00:00    345
2014-01-01 00:00:01    186
2014-01-01 00:00:02    157
2014-01-01 00:00:03    356
2014-01-01 00:00:04    116
2014-01-01 00:00:05     98
2014-01-01 00:00:06     73
2014-01-01 00:00:07    345
2014-01-01 00:00:08    417
2014-01-01 00:00:09    409
2014-01-01 00:00:10    364
2014-01-01 00:00:11    116
2014-01-01 00:00:12      4
2014-01-01 00:00:13    355
2014-01-01 00:00:14    395
2014-01-01 00:00:15    472
2014-01-01 00:00:16    230
2014-01-01 00:00:17    186
2014-01-01 00:00:18    401
2014-01-01 00:00:19      8
2014-01-01 00:00:20     36
2014-01-01 00:00:21    475
2014-01-01 00:00:22     54
2014-01-01 00:00:23    384
2014-01-01 00:00:24    336
2014-01-01 00:00:25    171
2014-01-01 00:00:26    335
2014-01-01 00:00:27    233
2014-01-01 00:00:28    190
2014-01-01 00:00:29    267
                      ... 
2014-01-01 00:01:10    260
2014-01-01 00:01:11    342
2014-01-01 00:01:12     41
2014-01-01 00:01:13     94
2014-01-01 00:01:14     48
2014-01-01 00:01:15    289
2

In [193]:
# Built in resampling
ts.resample('1Min',how='mean') # Resample secondly to 1Minutely

/Users/Aerlinger/.pyenv/versions/2.7.11/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).mean()
  from ipykernel import kernelapp as app


2014-01-01 00:00:00    261.05
2014-01-01 00:01:00    243.55
Freq: T, dtype: float64

In [194]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-194-5c9240a56f62>, line 2)

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
%matplotlib inline

df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

In [ ]:
df

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas